package org.es4j.serialization.json;

import org.es4j.dotnet.CultureInfo;
import org.es4j.dotnet.ResourceManager;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//   A strongly-typed resource class, for looking up localized strings, etc.
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
//[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
//[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
//internal
public class Messages {

    private static ResourceManager resourceMan;
    private static CultureInfo resourceCulture;

    //[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    private Messages() {
    }

    //   Returns the cached ResourceManager instance used by this class.
    //[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    //internal
    private static ResourceManager resourceManager;

    public static ResourceManager getResourceManager() {
        throw new UnsupportedOperationException("Not yet implemented");
        //if (Object.ReferenceEquals(resourceMan, null)) {
        //    ResourceManager temp = new ResourceManager("EventStore.Serialization.Messages", typeof(Messages).Assembly);
        //    resourceMan = temp;
        //}
        //return resourceMan;
    }

    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    //[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    //internal
    private static CultureInfo culture;

    public static CultureInfo getCulture() {
        return resourceCulture;
    }

    public static void setCulture(CultureInfo resourceCulture_) {
        resourceCulture = resourceCulture_;
    }

    // Looks up a localized string similar to Deserializing stream to object of type &apos;{0}&apos;..
    public static String DeserializingStream() {
        return ResourceManager.getString("DeserializingStream", resourceCulture);
    }

    //   Looks up a localized string similar to Registering type &apos;{0}&apos; as a known type..
    public static String RegisteringKnownType() {
        return ResourceManager.getString("RegisteringKnownType", resourceCulture);
    }

    //   Looks up a localized string similar to Serializing object graph of type &apos;{0}&apos;..
    public static String SerializingGraph() {
        return ResourceManager.getString("SerializingGraph", resourceCulture);
    }

    //   Looks up a localized string similar to Objects of type &apos;{0}&apos; are considered to be an array: &apos;{1}&apos;..
    public static String TypeIsArray() {
        return ResourceManager.getString("TypeIsArray", resourceCulture);
    }

    //   Looks up a localized string similar to The object to be serialized is of type &apos;{0}&apos;.  Using a typed serializer for the unknown type..
    public static String UsingTypedSerializer() {
        return ResourceManager.getString("UsingTypedSerializer", resourceCulture);
    }

    //   Looks up a localized string similar to The object to be serialized is of type &apos;{0}&apos;.  Using an untyped serializer for the known type..
    public static String UsingUntypedSerializer() {
        return ResourceManager.getString("UsingUntypedSerializer", resourceCulture);
    }
}
